using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScholarRescue.Models.Matching
{
    /// <summary>
    /// Stores the calculated match score between a writer and an order.
    /// Generated by the Intelligent Writer Matching Engine.
    /// Each field stores the weighted component score (0-100).
    /// </summary>
    public class WriterMatchScore
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int OrderId { get; set; }
        [ForeignKey(nameof(OrderId))]
        public virtual Order Order { get; set; } = null!;

        [Required, MaxLength(450)]
        public string WriterId { get; set; } = string.Empty;
        [ForeignKey(nameof(WriterId))]
        public virtual ApplicationUser Writer { get; set; } = null!;

        /// <summary>Final weighted match percentage (0-100).</summary>
        public double MatchPercentage { get; set; }

        /// <summary>Subject expertise component (0-100).</summary>
        public double ExpertiseScore { get; set; }

        /// <summary>Academic level qualification component (0-100).</summary>
        public double AcademicLevelScore { get; set; }

        /// <summary>Reliability score component (0-100).</summary>
        public double ReliabilityScore { get; set; }

        /// <summary>Client rating component (0-100).</summary>
        public double RatingScore { get; set; }

        /// <summary>Current capacity/availability component (0-100).</summary>
        public double CapacityScore { get; set; }

        /// <summary>Deadline compatibility component (0-100).</summary>
        public double DeadlineScore { get; set; }

        /// <summary>Recent performance component (0-100).</summary>
        public double PerformanceScore { get; set; }

        /// <summary>Quality score component (0-100).</summary>
        public double QualityScore { get; set; }

        /// <summary>Unweighted total before percentage normalization.</summary>
        public double TotalScore { get; set; }

        [MaxLength(1000)]
        public string? Explanation { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}