namespace ScholarRescue.Models.Enums
{
    /// <summary>
    /// Types of monitoring alerts that can be generated by the Order Monitoring Engine.
    /// </summary>
    public enum MonitoringAlertType
    {
        /// <summary>Order has been in the marketplace for 2+ hours with no applicants.</summary>
        NoApplicantsAfter2Hours,

        /// <summary>Urgent order has been in the marketplace for 30+ minutes with no applicants.</summary>
        UrgentNoApplicantsAfter30Min,

        /// <summary>Assigned writer has been inactive on an order for 24+ hours.</summary>
        WriterInactive24Hours,

        /// <summary>An order milestone deadline has passed without submission.</summary>
        MilestoneOverdue,

        /// <summary>A revision request is pending and the deadline has passed.</summary>
        RevisionOverdue
    }
}