using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScholarRescue.Migrations
{
    /// <inheritdoc />
    public partial class AddContactMessages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: table may already exist in production from manual SQL.
            // This migration was generated by EF Core but the table was never
            // actually created in production via `dotnet ef database update`.
            // Using raw SQL with IF NOT EXISTS to avoid crash on re-apply.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ContactMessages"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""Name"" character varying(100) NOT NULL,
                    ""Email"" character varying(200) NOT NULL,
                    ""Subject"" character varying(200) NOT NULL,
                    ""Message"" text NOT NULL,
                    ""SubmittedAt"" timestamp with time zone NOT NULL,
                    ""IsRead"" boolean NOT NULL,
                    ""AdminResponse"" text NULL,
                    ""RespondedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_ContactMessages"" PRIMARY KEY (""Id"")
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""ContactMessages"";");
        }
    }
}
