using System.ComponentModel.DataAnnotations;
using ScholarRescue.Models.Enums;

namespace ScholarRescue.Models
{
    /// <summary>
    /// Stores fraud detection alerts generated by the multi-account fraud detection engine.
    /// </summary>
    public class AccountFraudAlert
    {
        [Key]
        public int Id { get; set; }

        [Required, MaxLength(450)]
        public string UserId { get; set; } = string.Empty;
        public virtual ApplicationUser User { get; set; } = null!;

        /// <summary>AlertType: DuplicateEmail, DuplicatePhone, DuplicatePayment, SharedIP, SharedDevice, SuspiciousLogin</summary>
        [Required, MaxLength(50)]
        public string AlertType { get; set; } = string.Empty;

        /// <summary>Warning, HighRisk, Critical</summary>
        [Required, MaxLength(20)]
        public string Severity { get; set; } = "Warning";

        [Required, MaxLength(500)]
        public string Description { get; set; } = string.Empty;

        /// <summary>Computed risk score (0-100).</summary>
        public int RiskScore { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        [MaxLength(450)]
        public string? ReviewedByAdminId { get; set; }
        public virtual ApplicationUser? ReviewedByAdmin { get; set; }

        public DateTime? ReviewedAt { get; set; }

        /// <summary>Open, Resolved, Dismissed</summary>
        [MaxLength(20)]
        public string Status { get; set; } = "Open";
    }
}